apiVersion: v1
kind: Pod
metadata:
 name: nginx
 labels:
 app: myapp
spec:
 containers:
 - name: nginx
 image: 638450175311.dkr.ecr.ap-south-1.amazonaws.com/eksproj
 ports:
 - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
 name: mynodeport
spec:
 selector:
 app: myapp
 type: NodePort
